services:
  app:
    image: wsebastianml/webmicroservicios-app
    container_name: spring-microservice
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/songs-service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - app-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: "songs-service"
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge